name: household_data

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - pandas=0.19.0
  - numpy=1.11.2
  - pytables=3.2.2
  - xlrd=1.0.0  # pandas: excel i/o
  - openpyxl=2.4.0  # pandas: excel i/o
  - bottleneck  # accelerates some pandas operations
  - numexpr=2.6.1  # accelerates some pandas operations
  - notebook  # jupyter notebook
  - ipykernel=4.2.2 # older version of ipykernel to maek logging print to notebook instead of console
  - pytz=2016.7
  - pyyaml=3.12
  - requests=2.11.1

  - pip:
      - pycountry==1.20